keys:
  # Users
  - &users:
    - &brenix age1kky7jzc2x626xp4sfvpz7acytczqgdn7h2jxjqkjxzfd4kndcdxs8zr6ka
  # Hosts
  - &hosts:
    - &neo age13aug9ksxkwksqjl4ghd8u3cf5c9tseaxtw75s7mpksdes9edfp7qa47044
    - &trinity age1g6hk6frqedn4dlz2l3s06f6jl6f95eqfwk96qvtdws4ctgv60fdqesv664
    - &vm age1d59p9nrrg7dy94q0xsmep77yh84t4zr76l5s99h2nx52etqv859qzzvvd2
    - &morpheus age1ss38tfvw2emdjsgj4q7rullf47x2kd5qj8la7kctm8a3q4z7n9gscy0234

creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - age:
          - *brenix
          - *neo
          - *trinity
          - *vm
          - *morpheus
