keys:
  # Users
  - &users:
    - &brenix age1kky7jzc2x626xp4sfvpz7acytczqgdn7h2jxjqkjxzfd4kndcdxs8zr6ka
    - &pnicholson age13y24rlj2fehralwlexshgsv47q8e5uk03p9qk9qd42n7ccvd2ghqd5q5ry
  # Hosts
  - &hosts:
    - &neo age1qrduxvns6v5vuanhekjmqtk8lla0f9zz8xu8v3kudx9hjr3ruq6sjxswkn
    - &trinity age165ur9r8fxurzp40633y79ztuhkjzvp4afhu3q0juufspf7m2h9qqp7fux0
    - &vm age1d59p9nrrg7dy94q0xsmep77yh84t4zr76l5s99h2nx52etqv859qzzvvd2
    - &morpheus age1rvkgaxf3c9y0ywjnlxrummfq6e09eaz44l3ctnmm0wdn4tzvwspq22yg24
    - &pnicholson-1 age1f8ydnzdhugg8epwjtsealpaz08ym9g3p0dfwny0kjqp0mgj6n56q703fye

creation_rules:
  - path_regex: secrets.ya?ml$
    key_groups:
      - age:
          - *brenix
          - *pnicholson
          - *pnicholson-1
          - *neo
          - *trinity
          - *vm
          - *morpheus
