alias ..='cd ..'
alias cp='cp -i'
alias grep='grep --color=auto'
alias mkdir='mkdir -p -v'
alias l='ls -lhv'
alias la='ls -lAhv'
alias ls='ls -v --color=always --group-directories-first'

(( $+commands[brew] )) && alias u='brew update && brew upgrade && brew cleanup'
(( $+commands[nvim] )) && alias v='nvim'
(( $+commands[nvim] )) && alias vim='nvim'
(( $+commands[pacman] )) && alias remove='sudo pacman -Rscu'
(( $+commands[startx] )) && alias x='startx'
(( $+commands[sudoedit] )) && alias svim='sudoedit'
(( $+commands[systemctl] )) && alias s='sudo systemctl'
(( $+commands[virsh] )) && alias virsh='/usr/bin/virsh -c qemu:///system'
(( $+commands[virsh] )) && alias vm='virsh start win10'
(( $+commands[paru] )) && alias u='paru -Syu' && alias yay='paru'
(( $+commands[googler] )) && alias q='googler'
(( $+commands[googler] )) && alias define='googler -n 2 define'
