export EDITOR=nvim
export GREP_COLOR="1;31"
export HISTFILE="$HOME/.zsh-history"
export HISTSIZE=10000000
export PAGER="less -inMRF"
export SAVEHIST=10000000
export ZSH_CACHE_DIR=$HOME/.cache
export LC_CTYPE="en_US.UTF-8"
