# zmodload zsh/zprof

# -- Load commands
autoload -Uz compinit && compinit
autoload -Uz bashcompinit && bashcompinit

# -- Options
setopt alwaystoend         # Move cursor to end of word if completed in-word
setopt appendhistory       # allow multiple sessions to append to history
setopt autocd              # if a command cant be executed, cd into the dir
setopt autopushd           # make cd push the old dir onto the dir stack
setopt bashrematch         # enable bash regex matching
setopt clobber             # allow files to be clobbered
setopt completeinword      # not just at the end
setopt extendedglob        # allow reg-ex style matching
setopt hashlistall         # hash command paths when completion is attempted
setopt histexpiredupsfirst # ignore recording duplicate commands
setopt histignorealldups   # ignore recording duplicate commands
setopt histignorespace     # ignore recording commands prefixed with a space
setopt incappendhistory    # write to history file immediately, not when shell exits
setopt interactivecomments # enable comments on the command line
setopt menucomplete        # show menu completions
setopt noautomenu          # bash-like completion
setopt nobeep              # avoid beeping
setopt noflowcontrol       # no c-s/c-q output freezing
setopt nohup               # dont send SIGHUP to background processes when exiting
setopt null_glob           # dont error when no matching patterns exist when globbing
setopt promptsubst         # allow expansion in prompts
setopt pushdignoredups     # dont push the same dir twice
setopt unset               # dont error out when unset parameters are used

# -- Plugin manager
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
  command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi
source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh

# -- External configurations
for f in /etc/profiles/per-user/$USER/etc/profile.d/*.sh; do
  source $f
done

for f in $HOME/.zsh.d/*.zsh $HOME/.zsh.local.d/*.zsh; do
  source $f
done

# -- Completion
zcomet compinit

zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' rehash true
zstyle ':completion:*:approximate:' max-errors 'reply=( $((($#PREFIX+$#SUFFIX)/3 )) numeric )'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ":completion:*" completer _expand _complete _ignored _approximate
zstyle ":completion:*" insert-unambiguous true
zstyle ":completion:::*:default" menu no select
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path $ZSH_CACHE_DIR

# -- Prompt
eval "$(starship init zsh)"
