name: 'Thaw'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: snowfallorg/thaw-action@main
